server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:  "http://localhost:8192/"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: auth-service
          uri: http://localhost:8193
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8190
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
            - JwtAuthFilter
        - id: core-service
          uri: http://localhost:8189
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: order-service
          uri: http://localhost:8191
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-orders
            - JwtAuthFilter

jwt:
  secret: secretdofvndsfojvuhsd123123

